"""Türkiye Tek Düzen Hesap Planı — ana hesaplar (sınıf / grup / 3 haneli).

Kaynak: Muhasebe Sistemi Uygulama Genel Tebliği yapısına uygun standart ana hesaplar.
Alt hesaplar (120.01.0001 vb.) kullanıcı tarafından eklenir.
Fiş satırları yalnızca 120.01.0001 biçimindeki alt hesaplara yazılır.
"""

from __future__ import annotations

import re

# Fiş satırına yazılabilen alt hesap: 120.01.0001 → (ana).(2 hane).(4 hane)
FIS_ALT_HESAP_DESENI = re.compile(r"^\d{1,3}\.\d{2}\.\d{4}$")


def fis_icin_alt_hesap_mi(hesap_kodu: str) -> bool:
    """Muhasebe fişine yalnızca 120.01.0001 biçimindeki alt hesaplar yazılır."""
    return bool(FIS_ALT_HESAP_DESENI.match((hesap_kodu or "").strip()))


def fis_alt_hesap_zorunlu(hesap_kodu: str) -> None:
    kod = (hesap_kodu or "").strip()
    if not fis_icin_alt_hesap_mi(kod):
        raise ValueError(
            f"Bu hesaba fiş yazılamaz: {kod or '(boş)'}\n\n"
            "Muhasebe fişleri yalnızca alt hesaplara kesilir.\n"
            "Örnek biçim: 120.01.0001\n"
            "(Ana hesap / grup hesaplarına fiş oluşturulamaz.)"
        )


# (hesap_kodu, hesap_adi, hesap_turu)
# Sıra: önce sınıflar, sonra gruplar, sonra 3 haneli ana hesaplar

TDHP_ANA_HESAPLAR: tuple[tuple[str, str, str], ...] = (
    # ----- 1 DÖNEN VARLIKLAR -----
    ("1", "Dönen Varlıklar", "Aktif"),
    ("10", "Hazır Değerler", "Aktif"),
    ("100", "Kasa", "Aktif"),
    ("101", "Alınan Çekler", "Aktif"),
    ("102", "Bankalar", "Aktif"),
    ("103", "Verilen Çekler ve Ödeme Emirleri (-)", "Aktif"),
    ("108", "Diğer Hazır Değerler", "Aktif"),
    ("11", "Menkul Kıymetler", "Aktif"),
    ("110", "Hisse Senetleri", "Aktif"),
    ("111", "Özel Kesim Tahvil, Senet ve Bonoları", "Aktif"),
    ("112", "Kamu Kesimi Tahvil, Senet ve Bonoları", "Aktif"),
    ("118", "Diğer Menkul Kıymetler", "Aktif"),
    ("119", "Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("12", "Ticari Alacaklar", "Aktif"),
    ("120", "Alıcılar", "Aktif"),
    ("121", "Alacak Senetleri", "Aktif"),
    ("122", "Alacak Senetleri Reeskontu (-)", "Aktif"),
    ("126", "Verilen Depozito ve Teminatlar", "Aktif"),
    ("127", "Diğer Ticari Alacaklar", "Aktif"),
    ("128", "Şüpheli Ticari Alacaklar", "Aktif"),
    ("129", "Şüpheli Ticari Alacaklar Karşılığı (-)", "Aktif"),
    ("13", "Diğer Alacaklar", "Aktif"),
    ("131", "Ortaklardan Alacaklar", "Aktif"),
    ("132", "İştiraklerden Alacaklar", "Aktif"),
    ("133", "Bağlı Ortaklıklardan Alacaklar", "Aktif"),
    ("135", "Personelden Alacaklar", "Aktif"),
    ("136", "Diğer Çeşitli Alacaklar", "Aktif"),
    ("137", "Diğer Alacak Senetleri Reeskontu (-)", "Aktif"),
    ("138", "Şüpheli Diğer Alacaklar", "Aktif"),
    ("139", "Şüpheli Diğer Alacaklar Karşılığı (-)", "Aktif"),
    ("15", "Stoklar", "Aktif"),
    ("150", "İlk Madde ve Malzeme", "Aktif"),
    ("151", "Yarı Mamuller - Üretim", "Aktif"),
    ("152", "Mamuller", "Aktif"),
    ("153", "Ticari Mallar", "Aktif"),
    ("157", "Diğer Stoklar", "Aktif"),
    ("158", "Stok Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("159", "Verilen Sipariş Avansları", "Aktif"),
    ("17", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "Aktif"),
    ("170", "Yıllara Yaygın İnşaat ve Onarım Maliyetleri", "Aktif"),
    ("178", "Yıllara Yaygın İnşaat Enflasyon Düzeltme Hesabı", "Aktif"),
    ("179", "Taşeronlara Verilen Avanslar", "Aktif"),
    ("18", "Gelecek Aylara Ait Giderler ve Gelir Tahakkukları", "Aktif"),
    ("180", "Gelecek Aylara Ait Giderler", "Aktif"),
    ("181", "Gelir Tahakkukları", "Aktif"),
    ("19", "Diğer Dönen Varlıklar", "Aktif"),
    ("190", "Devreden KDV", "Aktif"),
    ("191", "İndirilecek KDV", "Aktif"),
    ("192", "Diğer KDV", "Aktif"),
    ("193", "Peşin Ödenen Vergiler ve Fonlar", "Aktif"),
    ("196", "Personel Avansları", "Aktif"),
    ("197", "İş Avansları", "Aktif"),
    ("198", "Diğer Çeşitli Dönen Varlıklar", "Aktif"),
    ("199", "Diğer Dönen Varlıklar Karşılığı (-)", "Aktif"),
    # ----- 2 DURAN VARLIKLAR -----
    ("2", "Duran Varlıklar", "Aktif"),
    ("22", "Ticari Alacaklar", "Aktif"),
    ("220", "Alıcılar", "Aktif"),
    ("221", "Alacak Senetleri", "Aktif"),
    ("222", "Alacak Senetleri Reeskontu (-)", "Aktif"),
    ("226", "Verilen Depozito ve Teminatlar", "Aktif"),
    ("229", "Şüpheli Alacaklar Karşılığı (-)", "Aktif"),
    ("23", "Diğer Alacaklar", "Aktif"),
    ("231", "Ortaklardan Alacaklar", "Aktif"),
    ("232", "İştiraklerden Alacaklar", "Aktif"),
    ("233", "Bağlı Ortaklıklardan Alacaklar", "Aktif"),
    ("235", "Personelden Alacaklar", "Aktif"),
    ("236", "Diğer Çeşitli Alacaklar", "Aktif"),
    ("237", "Diğer Alacak Senetleri Reeskontu (-)", "Aktif"),
    ("239", "Şüpheli Diğer Alacaklar Karşılığı (-)", "Aktif"),
    ("24", "Mali Duran Varlıklar", "Aktif"),
    ("240", "Bağlı Menkul Kıymetler", "Aktif"),
    ("241", "Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("242", "İştirakler", "Aktif"),
    ("243", "İştiraklere Sermaye Taahhütleri (-)", "Aktif"),
    ("244", "İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("245", "Bağlı Ortaklıklar", "Aktif"),
    ("246", "Bağlı Ortaklıklara Sermaye Taahhütleri (-)", "Aktif"),
    ("247", "Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("248", "Diğer Mali Duran Varlıklar", "Aktif"),
    ("249", "Diğer Mali Duran Varlıklar Karşılığı (-)", "Aktif"),
    ("25", "Maddi Duran Varlıklar", "Aktif"),
    ("250", "Arazi ve Arsalar", "Aktif"),
    ("251", "Yeraltı ve Yerüstü Düzenleri", "Aktif"),
    ("252", "Binalar", "Aktif"),
    ("253", "Tesis, Makine ve Cihazlar", "Aktif"),
    ("254", "Taşıtlar", "Aktif"),
    ("255", "Demirbaşlar", "Aktif"),
    ("256", "Diğer Maddi Duran Varlıklar", "Aktif"),
    ("257", "Birikmiş Amortismanlar (-)", "Aktif"),
    ("258", "Yapılmakta Olan Yatırımlar", "Aktif"),
    ("259", "Verilen Avanslar", "Aktif"),
    ("26", "Maddi Olmayan Duran Varlıklar", "Aktif"),
    ("260", "Haklar", "Aktif"),
    ("261", "Şerefiye", "Aktif"),
    ("262", "Kuruluş ve Örgütlenme Giderleri", "Aktif"),
    ("263", "Araştırma ve Geliştirme Giderleri", "Aktif"),
    ("264", "Özel Maliyetler", "Aktif"),
    ("267", "Diğer Maddi Olmayan Duran Varlıklar", "Aktif"),
    ("268", "Birikmiş Amortismanlar (-)", "Aktif"),
    ("269", "Verilen Avanslar", "Aktif"),
    ("27", "Özel Tükenmeye Tabi Varlıklar", "Aktif"),
    ("271", "Arama Giderleri", "Aktif"),
    ("272", "Hazırlık ve Geliştirme Giderleri", "Aktif"),
    ("277", "Diğer Özel Tükenmeye Tabi Varlıklar", "Aktif"),
    ("278", "Birikmiş Tükenme Payları (-)", "Aktif"),
    ("279", "Verilen Avanslar", "Aktif"),
    ("28", "Gelecek Yıllara Ait Giderler ve Gelir Tahakkukları", "Aktif"),
    ("280", "Gelecek Yıllara Ait Giderler", "Aktif"),
    ("281", "Gelir Tahakkukları", "Aktif"),
    ("29", "Diğer Duran Varlıklar", "Aktif"),
    ("291", "Gelecek Yıllarda İndirilecek KDV", "Aktif"),
    ("292", "Diğer KDV", "Aktif"),
    ("293", "Gelecek Yıllar İhtiyacı Stoklar", "Aktif"),
    ("294", "Elden Çıkarılacak Stoklar ve Maddi Duran Varlıklar", "Aktif"),
    ("295", "Peşin Ödenen Vergiler ve Fonlar", "Aktif"),
    ("297", "Diğer Çeşitli Duran Varlıklar", "Aktif"),
    ("298", "Stok Değer Düşüklüğü Karşılığı (-)", "Aktif"),
    ("299", "Birikmiş Amortismanlar (-)", "Aktif"),
    # ----- 3 KISA VADELİ YABANCI KAYNAKLAR -----
    ("3", "Kısa Vadeli Yabancı Kaynaklar", "Pasif"),
    ("30", "Mali Borçlar", "Pasif"),
    ("300", "Banka Kredileri", "Pasif"),
    ("301", "Finansal Kiralama İşlemlerinden Borçlar", "Pasif"),
    ("302", "Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)", "Pasif"),
    ("303", "Kısa Vadeli Çıkarılmış Tahviller", "Pasif"),
    ("304", "Tahvil Anapara Borç Taksit ve Faizleri", "Pasif"),
    ("305", "Çıkarılmış Diğer Menkul Kıymetler", "Pasif"),
    ("306", "Menkul Kıymetler İhraç Farkları (-)", "Pasif"),
    ("308", "Diğer Mali Borçlar", "Pasif"),
    ("309", "Diğer Mali Borçlar Faiz Tahakkuku", "Pasif"),
    ("32", "Ticari Borçlar", "Pasif"),
    ("320", "Satıcılar", "Pasif"),
    ("321", "Borç Senetleri", "Pasif"),
    ("322", "Borç Senetleri Reeskontu (-)", "Pasif"),
    ("326", "Alınan Depozito ve Teminatlar", "Pasif"),
    ("329", "Diğer Ticari Borçlar", "Pasif"),
    ("33", "Diğer Borçlar", "Pasif"),
    ("331", "Ortaklara Borçlar", "Pasif"),
    ("332", "İştiraklere Borçlar", "Pasif"),
    ("333", "Bağlı Ortaklıklara Borçlar", "Pasif"),
    ("335", "Personele Borçlar", "Pasif"),
    ("336", "Diğer Çeşitli Borçlar", "Pasif"),
    ("337", "Diğer Borç Senetleri Reeskontu (-)", "Pasif"),
    ("34", "Alınan Avanslar", "Pasif"),
    ("340", "Alınan Sipariş Avansları", "Pasif"),
    ("349", "Alınan Diğer Avanslar", "Pasif"),
    ("36", "Ödenecek Vergi ve Diğer Yükümlülükler", "Pasif"),
    ("360", "Ödenecek Vergi ve Fonlar", "Pasif"),
    ("361", "Ödenecek Sosyal Güvenlik Kesintileri", "Pasif"),
    ("368", "Vadesi Geçmiş Ertelenmiş veya Taksitlendirilmiş Vergi ve Diğer Yükümlülükler", "Pasif"),
    ("369", "Ödenecek Diğer Yükümlülükler", "Pasif"),
    ("37", "Borç ve Gider Karşılıkları", "Pasif"),
    ("370", "Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları", "Pasif"),
    ("371", "Dönem Kârının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)", "Pasif"),
    ("372", "Kıdem Tazminatı Karşılığı", "Pasif"),
    ("373", "Maliyet Giderleri Karşılığı", "Pasif"),
    ("379", "Diğer Borç ve Gider Karşılıkları", "Pasif"),
    ("38", "Gelecek Aylara Ait Gelirler ve Gider Tahakkukları", "Pasif"),
    ("380", "Gelecek Aylara Ait Gelirler", "Pasif"),
    ("381", "Gider Tahakkukları", "Pasif"),
    ("39", "Diğer Kısa Vadeli Yabancı Kaynaklar", "Pasif"),
    ("391", "Hesaplanan KDV", "Pasif"),
    ("392", "Diğer KDV", "Pasif"),
    ("393", "Merkez ve Şubeler Cari Hesabı", "Pasif"),
    ("397", "Sayım ve Tesellüm Fazlaları", "Pasif"),
    ("399", "Diğer Çeşitli Yabancı Kaynaklar", "Pasif"),
    # ----- 4 UZUN VADELİ YABANCI KAYNAKLAR -----
    ("4", "Uzun Vadeli Yabancı Kaynaklar", "Pasif"),
    ("40", "Mali Borçlar", "Pasif"),
    ("400", "Banka Kredileri", "Pasif"),
    ("401", "Finansal Kiralama İşlemlerinden Borçlar", "Pasif"),
    ("402", "Ertelenmiş Finansal Kiralama Borçlanma Maliyetleri (-)", "Pasif"),
    ("405", "Çıkarılmış Tahviller", "Pasif"),
    ("407", "Çıkarılmış Diğer Menkul Kıymetler", "Pasif"),
    ("408", "Menkul Kıymetler İhraç Farkları (-)", "Pasif"),
    ("409", "Diğer Mali Borçlar", "Pasif"),
    ("42", "Ticari Borçlar", "Pasif"),
    ("420", "Satıcılar", "Pasif"),
    ("421", "Borç Senetleri", "Pasif"),
    ("422", "Borç Senetleri Reeskontu (-)", "Pasif"),
    ("426", "Alınan Depozito ve Teminatlar", "Pasif"),
    ("429", "Diğer Ticari Borçlar", "Pasif"),
    ("43", "Diğer Borçlar", "Pasif"),
    ("431", "Ortaklara Borçlar", "Pasif"),
    ("432", "İştiraklere Borçlar", "Pasif"),
    ("433", "Bağlı Ortaklıklara Borçlar", "Pasif"),
    ("436", "Diğer Çeşitli Borçlar", "Pasif"),
    ("437", "Diğer Borç Senetleri Reeskontu (-)", "Pasif"),
    ("44", "Alınan Avanslar", "Pasif"),
    ("440", "Alınan Sipariş Avansları", "Pasif"),
    ("449", "Alınan Diğer Avanslar", "Pasif"),
    ("47", "Borç ve Gider Karşılıkları", "Pasif"),
    ("472", "Kıdem Tazminatı Karşılığı", "Pasif"),
    ("479", "Diğer Borç ve Gider Karşılıkları", "Pasif"),
    ("48", "Gelecek Yıllara Ait Gelirler ve Gider Tahakkukları", "Pasif"),
    ("480", "Gelecek Yıllara Ait Gelirler", "Pasif"),
    ("481", "Gider Tahakkukları", "Pasif"),
    ("49", "Diğer Uzun Vadeli Yabancı Kaynaklar", "Pasif"),
    ("492", "Gelecek Yıllara Ertelenen veya Terkin Edilen Vergiler ve Diğer Yükümlülükler", "Pasif"),
    ("493", "Tesise Katılma Payları", "Pasif"),
    ("499", "Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar", "Pasif"),
    # ----- 5 ÖZ KAYNAKLAR -----
    ("5", "Öz Kaynaklar", "Pasif"),
    ("50", "Ödenmiş Sermaye", "Pasif"),
    ("500", "Sermaye", "Pasif"),
    ("501", "Ödenmemiş Sermaye (-)", "Pasif"),
    ("502", "Sermaye Düzeltmesi Olumlu Farkları", "Pasif"),
    ("503", "Sermaye Düzeltmesi Olumsuz Farkları (-)", "Pasif"),
    ("52", "Sermaye Yedekleri", "Pasif"),
    ("520", "Hisse Senedi İhraç Primleri", "Pasif"),
    ("521", "Hisse Senedi İptal Kârları", "Pasif"),
    ("522", "Maddi Duran Varlık Yeniden Değerleme Artışları", "Pasif"),
    ("523", "İştirakler Yeniden Değerleme Artışları", "Pasif"),
    ("529", "Diğer Sermaye Yedekleri", "Pasif"),
    ("54", "Kâr Yedekleri", "Pasif"),
    ("540", "Yasal Yedekler", "Pasif"),
    ("541", "Statü Yedekleri", "Pasif"),
    ("542", "Olağanüstü Yedekler", "Pasif"),
    ("548", "Diğer Kâr Yedekleri", "Pasif"),
    ("549", "Özel Fonlar", "Pasif"),
    ("57", "Geçmiş Yıllar Kârları", "Pasif"),
    ("570", "Geçmiş Yıllar Kârları", "Pasif"),
    ("58", "Geçmiş Yıllar Zararları (-)", "Pasif"),
    ("580", "Geçmiş Yıllar Zararları (-)", "Pasif"),
    ("59", "Dönem Net Kârı (Zararı)", "Pasif"),
    ("590", "Dönem Net Kârı", "Pasif"),
    ("591", "Dönem Net Zararı (-)", "Pasif"),
    # ----- 6 GELİR TABLOSU -----
    ("6", "Gelir Tablosu Hesapları", "Gelir"),
    ("60", "Brüt Satışlar", "Gelir"),
    ("600", "Yurtiçi Satışlar", "Gelir"),
    ("601", "Yurtdışı Satışlar", "Gelir"),
    ("602", "Diğer Gelirler", "Gelir"),
    ("61", "Satış İndirimleri (-)", "Gelir"),
    ("610", "Satıştan İadeler (-)", "Gelir"),
    ("611", "Satış İskontoları (-)", "Gelir"),
    ("612", "Diğer İndirimler (-)", "Gelir"),
    ("62", "Satışların Maliyeti (-)", "Gider"),
    ("620", "Satılan Mamuller Maliyeti (-)", "Gider"),
    ("621", "Satılan Ticari Mallar Maliyeti (-)", "Gider"),
    ("622", "Satılan Hizmet Maliyeti (-)", "Gider"),
    ("623", "Diğer Satışların Maliyeti (-)", "Gider"),
    ("63", "Faaliyet Giderleri (-)", "Gider"),
    ("630", "Araştırma ve Geliştirme Giderleri (-)", "Gider"),
    ("631", "Pazarlama Satış ve Dağıtım Giderleri (-)", "Gider"),
    ("632", "Genel Yönetim Giderleri (-)", "Gider"),
    ("64", "Diğer Faaliyetlerden Olağan Gelir ve Kârlar", "Gelir"),
    ("640", "İştiraklerden Temettü Gelirleri", "Gelir"),
    ("641", "Bağlı Ortaklıklardan Temettü Gelirleri", "Gelir"),
    ("642", "Faiz Gelirleri", "Gelir"),
    ("643", "Komisyon Gelirleri", "Gelir"),
    ("644", "Konusu Kalmayan Karşılıklar", "Gelir"),
    ("645", "Menkul Kıymet Satış Kârları", "Gelir"),
    ("646", "Kambiyo Kârları", "Gelir"),
    ("647", "Reeskont Faiz Gelirleri", "Gelir"),
    ("648", "Enflasyon Düzeltmesi Kârları", "Gelir"),
    ("649", "Diğer Olağan Gelir ve Kârlar", "Gelir"),
    ("65", "Diğer Faaliyetlerden Olağan Gider ve Zararlar (-)", "Gider"),
    ("653", "Komisyon Giderleri (-)", "Gider"),
    ("654", "Karşılık Giderleri (-)", "Gider"),
    ("655", "Menkul Kıymet Satış Zararları (-)", "Gider"),
    ("656", "Kambiyo Zararları (-)", "Gider"),
    ("657", "Reeskont Faiz Giderleri (-)", "Gider"),
    ("658", "Enflasyon Düzeltmesi Zararları (-)", "Gider"),
    ("659", "Diğer Olağan Gider ve Zararlar (-)", "Gider"),
    ("66", "Finansman Giderleri (-)", "Gider"),
    ("660", "Kısa Vadeli Borçlanma Giderleri (-)", "Gider"),
    ("661", "Uzun Vadeli Borçlanma Giderleri (-)", "Gider"),
    ("67", "Olağandışı Gelir ve Kârlar", "Gelir"),
    ("671", "Önceki Dönem Gelir ve Kârları", "Gelir"),
    ("679", "Diğer Olağandışı Gelir ve Kârlar", "Gelir"),
    ("68", "Olağandışı Gider ve Zararlar (-)", "Gider"),
    ("680", "Çalışmayan Kısım Gider ve Zararları (-)", "Gider"),
    ("681", "Önceki Dönem Gider ve Zararları (-)", "Gider"),
    ("689", "Diğer Olağandışı Gider ve Zararlar (-)", "Gider"),
    ("69", "Dönem Net Kârı veya Zararı", "Gelir"),
    ("690", "Dönem Kârı veya Zararı", "Gelir"),
    ("691", "Dönem Kârı Vergi ve Diğer Yasal Yükümlülük Karşılıkları (-)", "Gider"),
    ("692", "Dönem Net Kârı veya Zararı", "Gelir"),
    # ----- 7 MALİYET HESAPLARI (7/A özeti) -----
    ("7", "Maliyet Hesapları", "Gider"),
    ("70", "Maliyet Muhasebesi Bağlantı Hesapları", "Gider"),
    ("700", "Maliyet Muhasebesi Bağlantı Hesabı", "Gider"),
    ("701", "Maliyet Muhasebesi Yansıtma Hesabı", "Gider"),
    ("71", "Direkt İlk Madde ve Malzeme Giderleri", "Gider"),
    ("710", "Direkt İlk Madde ve Malzeme Giderleri", "Gider"),
    ("711", "Direkt İlk Madde ve Malzeme Yansıtma Hesabı", "Gider"),
    ("712", "Direkt İlk Madde ve Malzeme Fiyat Farkı", "Gider"),
    ("713", "Direkt İlk Madde ve Malzeme Miktar Farkı", "Gider"),
    ("72", "Direkt İşçilik Giderleri", "Gider"),
    ("720", "Direkt İşçilik Giderleri", "Gider"),
    ("721", "Direkt İşçilik Ücret Farkları", "Gider"),
    ("722", "Direkt İşçilik Süre (Zaman) Farkları", "Gider"),
    ("73", "Genel Üretim Giderleri", "Gider"),
    ("730", "Genel Üretim Giderleri", "Gider"),
    ("731", "Genel Üretim Giderleri Yansıtma Hesabı", "Gider"),
    ("732", "Genel Üretim Giderleri Bütçe Sapmaları", "Gider"),
    ("733", "Genel Üretim Giderleri Verimlilik Sapmaları", "Gider"),
    ("74", "Hizmet Üretim Maliyeti", "Gider"),
    ("740", "Hizmet Üretim Maliyeti", "Gider"),
    ("741", "Hizmet Üretim Maliyeti Yansıtma Hesabı", "Gider"),
    ("75", "Araştırma ve Geliştirme Giderleri", "Gider"),
    ("750", "Araştırma ve Geliştirme Giderleri", "Gider"),
    ("751", "Araştırma ve Geliştirme Giderleri Yansıtma Hesabı", "Gider"),
    ("76", "Pazarlama Satış ve Dağıtım Giderleri", "Gider"),
    ("760", "Pazarlama Satış ve Dağıtım Giderleri", "Gider"),
    ("761", "Pazarlama Satış ve Dağıtım Giderleri Yansıtma Hesabı", "Gider"),
    ("77", "Genel Yönetim Giderleri", "Gider"),
    ("770", "Genel Yönetim Giderleri", "Gider"),
    ("771", "Genel Yönetim Giderleri Yansıtma Hesabı", "Gider"),
    ("78", "Finansman Giderleri", "Gider"),
    ("780", "Finansman Giderleri", "Gider"),
    ("781", "Finansman Giderleri Yansıtma Hesabı", "Gider"),
    ("79", "Gider Çeşitleri", "Gider"),
    ("790", "İlk Madde ve Malzeme Giderleri", "Gider"),
    ("791", "İşçi Ücret ve Giderleri", "Gider"),
    ("792", "Memur Ücret ve Giderleri", "Gider"),
    ("793", "Dışarıdan Sağlanan Fayda ve Hizmetler", "Gider"),
    ("794", "Çeşitli Giderler", "Gider"),
    ("795", "Vergi, Resim ve Harçlar", "Gider"),
    ("796", "Amortismanlar ve Tükenme Payları", "Gider"),
    ("797", "Finansman Giderleri", "Gider"),
    ("798", "Gider Çeşitleri Yansıtma Hesabı", "Gider"),
    ("799", "Üretim Maliyeti Fark Hesapları", "Gider"),
    # ----- 9 NAZIM HESAPLAR -----
    ("9", "Nazım Hesaplar", "Nazım"),
    ("90", "Nazım Hesaplar", "Nazım"),
    ("900", "Nazım Hesaplar", "Nazım"),
    ("901", "Teminat Mektupları", "Nazım"),
    ("902", "Teminata Verilen Menkul Kıymetler", "Nazım"),
    ("903", "Teminat Senetleri", "Nazım"),
    ("909", "Diğer Nazım Hesaplar", "Nazım"),
)


def tdhp_ust_kodu(hesap_kodu: str) -> str | None:
    """Tek düzen koduna göre üst hesap kodunu döner."""
    kod = (hesap_kodu or "").strip()
    if len(kod) <= 1:
        return None
    if len(kod) == 2:
        return kod[0]
    if len(kod) == 3:
        return kod[:2]
    # Noktalı alt hesaplar: 120.01 → 120
    if "." in kod:
        return kod.rsplit(".", 1)[0]
    return kod[:-1]
